# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c10754e233f40fc75e08855bd8bd41b0d5313e475b40408869ce21d708b04a25114c1504e8267decbabaa9cf6ebd1f1ca2474776acf7345a8f018f3a59ad6d84

test:
  secret_key_base: 2aa1d5168cf8f374013dee08555b9c3de9dab53d9825a4c9b4be96401bd4506d3e3d2de36c5d89dc75a8fef2639507bf0946529f1a2041e7eb14b1517c04a279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
